### ISSUE TITLE
Alertmanager build fails in default main branch

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/alertmanager#26]
**What did you do?**

Tried building alertmanager binary.

**What did you expect to see?**

Expected to build Alertmanager binary and Docker image without any issue.

**What did you see instead? Under which circumstances?**

Got the error below when trying to build the Alertmanager binary:

```
# golang.org/x/net/http2
Error: /go/pkg/mod/golang.org/x/net@v0.23.0/http2/transport.go:1096:13: tc.NetConn undefined (type *tls.Conn has no field or method NetConn)
note: module requires Go 1.18
!! command failed: build -o .build/linux-amd64/alertmanager -ldflags -X github.com/prometheus/common/version.Version=0.23.0 -X github.com/prometheus/common/version.Revision=bda6d1956a40d49536cd0b0e5fa51a4d692b0f76 -X github.com/prometheus/common/version.Branch=HEAD -X github.com/prometheus/common/version.BuildUser=root@889b74d02581 -X github.com/prometheus/common/version.BuildDate=20240527-12:04:26  -extldflags '-static' -a -tags netgo github.com/prometheus/alertmanager/cmd/alertmanager: exit status 2
make: *** [Makefile.common:243: common-build] Error 1
!! The base builder docker image exited unexpectedly: exit status 2
make: *** [Makefile.common:248: common-crossbuild] Error 1
Error: Process completed with exit code 2.
```

This issue was most definitely introduced in this PR: https://github.com/SigNoz/alertmanager/pull/25

**Environment**

* System information: **Linux AMD**

* Alertmanager version: `main`

* Prometheus version: `NA`

* Alertmanager configuration file: `NA`

* Prometheus configuration file: `NA`

* Logs: `NA`

**Comment by srikanthccv** [comment]
Fixed on main
