### ISSUE TITLE
missing metrics labels does not trigger alerts

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/alertmanager#6]
#### Alertmanager version: v0.23.1

**What did you do?**

I created alerts for specific metrics with some label, let's say `endpoint: example.com/health` 

**What did you expect to see?**

expected the alerts to be triggered when that specific metrics with the specific label does not exist any longer.

**What did you see instead? Under which circumstances?**

no alerts triggered when the label or the metrics itself was missing.

**Comment by srikanthccv** [comment]
The alert won't be triggered if the label goes missing. This is a bug. Please see https://github.com/SigNoz/signoz/pull/3245
